version: "3"

volumes:
  mariadb_volume:
    name: mariadb_volume
    driver: local
    driver_opts:
      device: /Users/qfrederi/Inception/data/mariadb
      #device: /home/qfrederi/data/wordpress
      o: bind
      type: none
  wordpress_volume:
    name: wordpress_volume
    driver: local
    driver_opts:
      device: /Users/qfrederi/Inception/data/wordpress
      #device: /home/qfrederi/data/mariadb
      type: none
      o: bind

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb/.
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - network
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOSTNAME=${MYSQL_HOSTNAME}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress/.
    depends_on:
      - mariadb
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - network
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOSTNAME=${MYSQL_HOSTNAME}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - WP_ADMIN=${WP_ADMIN}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_USER=${WP_USER}
      - WP_USER_PASSWORD=${WP_USER_PASSWORD}
      - DOMAIN_NAME=${DOMAIN_NAME}
  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx/.
    depends_on:
      - wordpress
    volumes:
      - wordpress_volume:/var/www/html
    ports:
      - "443:443"
    networks:
      - network
    restart: always
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - SSL_COUNTRY=${SSL_COUNTRY}
      - SSL_STATE=${SSL_STATE}
      - SSL_LOCALITY=${SSL_LOCALITY}
      - SSL_ORGANIZATION=${SSL_ORGANIZATION}

networks:
  network:
    driver: bridge