version: "3"

volumes:
  mariadb_volume:
    name: mariadb
    driver: local
    driver_opts:
      device: /Users/qfrederi/Desktop/testmaria
      o: bind
      type: none

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - network
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOSTNAME=${MYSQL_HOSTNAME}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

networks:
  network:
    driver: bridge